backtest:
  commission: 0.001
  initial_cash: 100000
  min_commission: 0.99
data:
  pickle_file: data/finmem_data/stock_data_4stocks_2014_2019.pkl
dqn:
  action_dim: 3
  batch_size: 64
  epsilon_decay: 0.995
  epsilon_end: 0.1
  epsilon_start: 1.0
  gamma: 0.99
  hidden_dim: 256
  lr: 0.001
  max_episodes: 50
  state_dim: 120
  tau: 0.005
experiment:
  init_max_rounds: 5
  init_min_valid: 3
  max_iterations: 3
  sample_count: 6
  test_period:
  - '2019-01-01'
  - '2019-12-31'
  tickers:
  - TSLA
  - NFLX
  - AMZN
  - MSFT
  train_period:
  - '2014-01-01'
  - '2016-12-31'
  val_period:
  - '2017-01-01'
  - '2018-12-31'
intrinsic:
  weight: 0.02
llm:
  api_key: sk-gtO2lC26gUwH8PeZpQVnf5HC5ZsI9ckTZBrtbafX0HdMaiwL
  base_url: https://api.chatanywhere.com.cn/v1
  max_tokens: 2000
  model: gpt-4o-mini
  temperature: 0.7
output:
  log_dir: logs
  output_dir: exp4.7/result_W1_test2019
  save_results: true
